# Generated by Django 3.2.5 on 2021-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='photos.Profile'),
        ),
    ]
